# Config file for btop v.1.4.6

#* Name of a btop++/bpytop/bashtop formatted ".theme" file, "Default" and "TTY" for builtin themes.
color_theme = "Default"

#* If the theme set background should be shown, set to False if you want terminal background transparency.
theme_background = false

#* Define presets for the layout of the boxes. Preset 0 is always all boxes shown with default settings. Max 9 presets.
#* Preset 1: CPU + Processes
#* Preset 2: Memory + Processes
presets = "cpu:1:default,proc:1:default mem:1:default,proc:1:default"

#* Rounded corners on boxes
rounded_corners = true

#* Graph symbol to use for graph creation
graph_symbol = "braille"

#* Shown boxes
shown_boxes = "cpu mem net proc"

#* Update time in milliseconds
update_ms = 2000

#* Processes sorting
proc_sorting = "cpu lazy"

#* Reverse sorting order
proc_reversed = false

#* Show processes as a tree
proc_tree = false

#* Use the cpu graph colors in the process list
proc_colors = true

#* Use a darkening gradient in the process list
proc_gradient = true

#* If process cpu usage should be of the core it's running on or usage of the total available cpu power
proc_per_core = false

#* Show process memory as bytes instead of percent
proc_mem_bytes = true

#* Show cpu graph for each process
proc_cpu_graphs = true

#* Show battery stats in top right if battery is present
show_battery = true

#* Automatically save current settings to config file on exit
save_config_on_exit = true
