# btop cpu-only config
color_theme = "Default"
theme_background = false
shown_boxes = "cpu proc"
update_ms = 2000
proc_sorting = "cpu lazy"
proc_gradient = true
proc_cpu_graphs = false
cpu_single_graph = true
show_cpu_freq = false
show_coretemp = false
check_temp = true
show_uptime = false
rounded_corners = true
graph_symbol = "braille"
save_config_on_exit = false
